server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost/EmployeesManagementSystem
    username: alejoba1097
    password: A801b5e55f2*

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect