server:
  port: 8090

spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/EMS To be used without Docker
    url: jdbc:mysql://mysql_db/EMS
    username: alejoba1097
    password: A801b5e55f2*

  jpa:
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true